static_resources:
  listeners:
    - name: listener_1
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{default(envoy_port, 8080) | uint32}}
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: V4_ONLY
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"] # Web page cluster domain
                      routes:
                        - match:
                            prefix: "/api/authorization/"
                          route:
                            cluster: auth
                            prefix_rewrite: "/"
                        - match:
                            prefix: "/api/hydroservice/"
                          route:
                            cluster: api
                            prefix_rewrite: "/"
                        - match:
                            prefix: "/"
                          route:
                            cluster: frontend
                

  clusters:
    - name: "api"
      connect_timeout: 0.25s
      type: STATIC
      load_assignment:
        cluster_name: "api"
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "127.0.0.1"
                      port_value: 5001
    - name: "auth"
      connect_timeout: 0.25s
      type: STATIC
      load_assignment:
        cluster_name: "auth"
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "127.0.0.1"
                      port_value: 5002
    - name: "frontend"
      connect_timeout: 5s
      type: STATIC
      load_assignment:
        cluster_name: "frontend"
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 5000