#/bin/bash

DOTNET_ENV_DATABASE_HOST=localhost \
DOTNET_ENV_DATABASE_PORT=10150 \
DOTNET_ENV_DATABASE_USER=postgres \
DOTNET_ENV_DATABASE_PASSWORD=password \
DOTNET_ENV_DATABASE_NAME=api_db \
DOTNET_ENV_PISSIR_ISS=https://appweb.andreabarchietto.it \
DOTNET_ENV_PISSIR_AUD=https://pissir.andreabarchietto.it \
DOTNET_ENV_WEBSERVER_BOUND=0.0.0.0:8000 \
DOTNET_ENV_MQTT_HOST=localhost \
DOTNET_ENV_MQTT_PORT=1883 \
DOTNET_ENV_MQTT_USER=mosquitto \
DOTNET_ENV_MQTT_PASSWORD=password \
DOTNET_ENV_MQTT_POOLSIZE=5 \
DOTNET_ENV_MQTT_PERCLIENTCAPACITY=15 \
DOTNET_ENV_AUTH_URI=http://localhost:10154 \
dotnet run
